services:
  - type: web
    name: spooky-db
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api_server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: NEON_CONN_STRING
        sync: false
